#!/bin/bash

source="example/book.txt"
foxsl="example/fo.xsl"
fopconf="example/fop.xconf"
target="Book.pdf"
output=".output"

requirements=(asciidoc xsltproc python pygmentize fop)

for prog in "${requirements[@]}" ; do
  which $prog 2>&1 > /dev/null || {
    echo "You don't seem to have $prog installed."
    echo "Maybe you can install it like this:"
    echo ""
    echo "    sudo apt-get install $prog"
    echo ""
    exit 1
  }
done

[ -e "$target" ] && rm "$target"
rm -rf "$output"
mkdir "$output"

# Run asciidoc on your book's source and emit a DocBook XML file
asciidoc -b docbook -o "$output/book.xml" "$source"

# Add syntax annotation to DocBook code segments
./scripts/highlight docbook "$output/book.xml" example

# Convert the DocBook file to XSL-FO using the XSL file fo.xsl. You should make
# any formatting changes you want by editing that file.
xsltproc -o "$output/book.fo" "$foxsl" "$output/book.xml"

# Use syntax annotations in code blocks to highlight code
./scripts/highlight fo "$output/book.fo" example

# Take the XSL-FO output and convert it into a PDF. The config for this lives
# in fop.xconf, and tells the PDF renderer where to find fonts on your system
# and so on.
fop -c "$fopconf" -fo "$output/book.fo" -pdf "$target"

