#!/bin/bash

source="$1"
foxsl="$2"
fopconf="$3"
target="$4"
output=".output"

if [ -z "$source" ] ; then
  echo "Usage: ./build SOURCE FO_XSL FOP_CONF TARGET"
  echo "e.g.: ./build example/book.asc example/fo.xsl example/fop.xconf Book.pdf"
  exit 1
fi

requirements=(asciidoc xsltproc fop)

for prog in "${requirements[@]}" ; do
  which $prog 2>&1 > /dev/null || {
    echo "You don't seem to have $prog installed."
    echo "Maybe you can install it like this:"
    echo ""
    echo "    sudo apt-get install $prog"
    echo ""
    exit 1
  }
done

[ -e "$target" ] && rm "$target"
rm -rf "$output"
mkdir "$output"

# This runs asciidoc on your book's source and emits a DocBook XML file
asciidoc -b docbook -o "$output/book.xml" "$source"

# This converts the DocBook file to XSL-FO using the XSL file fo.xsl. You should
# make any formatting changes you want by editing that file.
xsltproc -o "$output/book.fo" "$foxsl" "$output/book.xml"

# This takes the XSL-FO output and converts it into a PDF. The config for this
# lives in fop.xconf, and tells the PDF renderer where to find fonts on your
# system and so on.
fop -c "$fopconf" -fo "$output/book.fo" -pdf "$target"

