PYGMENTS_THEME = {
    ('bp',):                { 'color': '#999' },
    ('c1',):                { 'color': '#998', 'style': 'italic' },
    ('ch',):                {},
    ('cp', 'cpf'):          { 'color': '#999', 'weight': 'bold' },
    ('dl',):                {},
    ('gd',):                { 'background': '#fdd' },
    ('gh',):                { 'color': '#999' },
    ('gi',):                { 'background': '#dfd' },
    ('gu',):                { 'color': '#aaa' },
    ('k', 'kd', 'kp'):      { 'weight': 'bold' },
    ('kt',):                { 'color': '#458', 'weight': 'bold' },
    ('m', 'mf', 'mh', 'mi', 'mo'): { 'color': '#099' },
    ('n', 'p'):             {},
    ('na', 'no', 'nv'):     { 'color': '#008080' },
    ('nb',):                { 'color': '#0086b3' },
    ('nc',):                { 'color': '#458', 'weight': 'bold' },
    ('nf',):                { 'color': '#900', 'weight': 'bold' },
    ('nn',):                { 'color': '#555' },
    ('nt',):                { 'color': '#000080' },
    ('nx',):                {},
    ('o', 'ow'):            { 'weight': 'bold' },
    ('s', 's1', 's2', 'sb', 'sc', 'se', 'sh', 'si', 'sx'): { 'color': '#d14' },
    ('sr',):                { 'color': '#009926' },
    ('ss',):                { 'color': '#990073' },
    ('vg', 'vi'):           { 'color': '#008080' },
}
