#!/usr/bin/env python

import sys
import re
from xml.dom.minidom import Node, parse, parseString
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import get_formatter_by_name

format = sys.argv[1]
target = sys.argv[2]
path   = sys.argv[3]
xml    = parse(target)

sys.path.append(path)
import syntax

def get_theme(type):
    settings = syntax.PYGMENTS_THEME
    for tags in settings:
        if type in tags: return settings[tags]
    return {}

def highlight_block(xml, block, format):
    for child in block.childNodes:
        if child.nodeType != Node.TEXT_NODE: continue
        
        pattern = '^#:highlight: (\S+)\n'
        code    = child.nodeValue
        match   = re.search(pattern, code)
        
        if match == None: continue
        
        lexer     = get_lexer_by_name(match.group(1))
        formatter = get_formatter_by_name('html')
        code      = re.sub(pattern, '', code)
        
        doc = parseString(highlight(code, lexer, formatter))
        
        for node in doc.getElementsByTagName('pre')[0].childNodes:
            if node.nodeType == Node.TEXT_NODE:
                block.insertBefore(xml.createTextNode(node.nodeValue), child)
            else:
                span = highlight_node(xml, node, format)
                block.insertBefore(span, child)
        
        block.removeChild(child)

def highlight_node(xml, node, format):
    theme  = get_theme(node.getAttribute('class'))
    color  = theme.get('color', '#000')
    style  = theme.get('style', 'normal')
    weight = theme.get('weight', 'normal')
    
    if format == 'fo':
        span = xml.createElement('fo:inline')
        span.setAttribute('color', color)
        span.setAttribute('font-style', style)
        span.setAttribute('font-weight', weight)
    elif format == 'html':
        span = xml.createElement('span')
        css = 'color: ' + color + '; font-style: ' + style + '; font-weight: ' + weight
        span.setAttribute('style', css)
    
    span.appendChild(xml.createTextNode(node.childNodes[0].nodeValue))
    return span

if format == 'docbook':
    for listing in xml.getElementsByTagName('programlisting'):
        lang = listing.getAttribute('language')
        code = listing.childNodes[0].nodeValue
        text = xml.createTextNode('#:highlight: ' + lang + '\n' + code)
        listing.removeChild(listing.childNodes[0])
        listing.appendChild(text)

elif format == 'fo':
    for block in xml.getElementsByTagName('fo:block'):
        highlight_block(xml, block, 'fo')

elif format == 'html':
    for block in xml.getElementsByTagName('pre'):
        if (block.getAttribute('class') != 'programlisting'): continue
        highlight_block(xml, block, 'html')

file = open(target, 'w')
file.write(xml.toxml().encode('utf-8'))
file.close()

